# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 04:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=100)),
                ('primary', models.CharField(max_length=300)),
                ('sub', models.CharField(max_length=300, null=True)),
                ('quantity', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=300)),
                ('difficulty', models.CharField(max_length=100)),
                ('ingcate', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('kcal', models.IntegerField()),
                ('vector', models.BinaryField(null=True)),
                ('imagepath', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecomLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BinaryField(null=True)),
                ('aprob', models.FloatField(default=0.0)),
                ('actual', models.IntegerField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prefer', models.BinaryField(null=True)),
                ('diet', models.BooleanField(default=False)),
                ('hate', models.CharField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
