# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170110_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingChecker',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
