# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-10 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_recipe_ingchecker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingChecker',
            new_name='ingchecker',
        ),
    ]
